### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [ceceliahavens/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by ceceliahavens** [comment]
I hope I figured it out. I stuck  <meta name="viewport" content="width=device-width, initial-scale=1">  in the head of my application.html.erb and then went to my master.css.scss and placed the following: @-ms-viewport{
  width: device-width;
}

Let me know if I am on the right track. with heroku down I can't push to heroku or pull it up on any mobile device to see how it is responding. it looks fine on my computer with the screen shrunk down as thin as I can get it.

**Comment by ceceliahavens** [comment]
for some reason even though I typed in the code, i used it is visible when I type it when I hit comment it disappears from the comment. when i click edit to add it back it is there...the code I used was  a  meta name viewport medly that doesn't show up if I type it for you.

**Comment by kenmazaika** [comment]
Thumbs up cecelia.  The meta tag in application.html.erb was exact right!  Thumbs up!
